### ISSUE TITLE
Add TabLayout

### ISSUE THREAD

**Issue by dmarusic35** [ikocijan/MagicViews#18]
Hello Ivan, it would be great to have MagicTabLayout so we can change fonts :)

**Comment by ikocijan** [comment]
MagicTabLayout is added and it will be available in 3.0.1

For now you can only set font programatically and after tabs have been set up:

        tabLayout.addTab(tabLayout.newTab().setText("Tab 1"));
        tabLayout.addTab(tabLayout.newTab().setText("Tab 2"));
        tabLayout.addTab(tabLayout.newTab().setText("Tab 3"));
        tabLayout.setFont("galaxyfaraway.ttf");

The reason for this is because the libarary has to go through all tabs in TabLayout in order to set font. It's possible to add an option to set Typface automatically when new tab is added but in that case, if we have for example 3 tabs the libaray would set typface on first tab 3 times which is inefficient. That's why this is the only option at the moment.
